### ISSUE TITLE
The EDF server blocks requests.get() - SOLVED

### ISSUE THREAD

**Issue by salmanshahid8** [apallier/alerte-ejp#1]
I have been looking for a web API EJP EDF. Kudos to you who developed it a few years ago.

When I run it, the requests.get(ejp_link) give me an error that the EDF server is blocking my requests. So after some trials and google searches, I found a way to deflect the situation by blinding the EDF server with a header.

```
import requests
from datetime import datetime

headers = {'user-agent':'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0'}

range = range(1,30,1)
for date in range:
    date_ = datetime(year=2020, month=1, day=date)
    date_str = date_.strftime("%Y-%m-%d")
    EJP = "https://particulier.edf.fr/bin/edf_rc/servlets/ejptemponew?Date_a_remonter={}&TypeAlerte=EJP".format(date_str)
    request = requests.get(EJP, headers=headers)
    request_dict = request.json()
    status = request_dict['JourJ1'][ZONE]
    print("Date: {}, Status: {}".format(date_str, status))
```

It is working. Will be great if also committed in the project file.

**Comment by apallier** [comment]
Hi @salmanshahid8,
Thank you. I didn't know that someone was still using it :)
Alexis
